# 개발 환경용 Docker Compose
version: '3.8'

services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15-alpine
    container_name: ai-call-postgres
    environment:
      POSTGRES_DB: ai_call_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai-call-network

  # Redis 캐시
  redis:
    image: redis:7-alpine
    container_name: ai-call-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai-call-network

  # pgAdmin (데이터베이스 관리 도구)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ai-call-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ai-call.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - ai-call-network

  # MinIO (음성 파일 저장소)
  minio:
    image: minio/minio:latest
    container_name: ai-call-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"    # API 포트
      - "9001:9001"    # 웹 콘솔 포트
    volumes:
      - minio_data:/data
    networks:
      - ai-call-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  ai-call-network:
    driver: bridge
